permalink: pretty
highlighter: rouge
url: "https://bushidocodes.github.io"
baseurl: "/playbook"

collections:
  - plays

markdown: kramdown

sass:
    sass_dir: assets/_sass

kramdown:
  auto_ids: false